version: '3.9'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6380:6379"
    command: ["redis-server", "--bind", "0.0.0.0", "--port", "6379"]
  
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.39
    restart: always
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686
      - 14268:14268

  prometheus:
    image: prom/prometheus:v2.24.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
  
  api:
    image: simple-bank-api
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres
      - redis
    entrypoint:
      [
        "/wait-for.sh",
        "postgres:5432",
        "--",
        "/start.sh",
      ]
    command: [ "./main" ]

volumes:
  postgres_data:
  prometheus_data:
  grafana-storage:
    